platform :ios, '13.0'
use_frameworks! :linkage => :static

target 'HXMediaPickerHarness' do
  pod 'HXMediaPicker', :path => '..'
  pod 'HXPhotoPicker', :git => 'https://github.com/wowbby/HXPhotoPicker.git', :tag => '5.0.6'

  target 'MediaPickerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_TESTABILITY'] = 'YES' if config.name == 'Debug'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
